server:
  port: 8001

spring:
  rabbitmq:
    host: 192.168.199.175
    port: 5672
    username: root
    password: root
    virtual-host: /
    publisher-confirms: true #开启消息确认机制
    publisher-returns: true #支持消息发送失败返回队列
