server:
  port: 8002

spring:
  rabbitmq:
    host: 192.168.199.175
    port: 5672
    username: root
    password: root
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual